name: llmcvrs
channels:
  - conda-forge
  - pytorch
  - gpytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - arrow-cpp=19.0.0
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0=openblas
  - boost-cpp=1.82.0
  - botorch=0.13.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - conllu=4.4.1
  - dataclasses=0.8
  - datasets=1.12.1
  - dill=0.3.8
  - et_xmlfile=1.1.0
  - expat=2.6.4
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gpytorch=1.14
  - huggingface_hub=0.0.17
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - inflate64=0.3.1
  - jaxtyping=0.2.36
  - jinja2=3.1.5
  - joblib=1.4.2
  - jpeg=9e
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - libxslt=1.1.41
  - libzlib=1.2.13
  - linear_operator=0.6
  - llvm-openmp=14.0.6
  - lxml=5.3.0
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multipledispatch=0.6.0
  - multiprocess=0.70.15
  - multivolumefile=0.2.3
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.1
  - opt_einsum=3.4.0
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0
  - propcache=0.2.0
  - psutil=5.9.0
  - py7zr=0.20.5
  - pyarrow=19.0.0
  - pybcj=1.0.1
  - pycryptodomex=3.21.0
  - pyppmd=1.0.0
  - pyre-extensions=0.0.32
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzstd=0.16.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=75.8.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - texttable=1.6.4
  - threadpoolctl=3.5.0
  - tiktoken=0.9.0
  - tk=8.6.14
  - torchvision=0.20.1
  - tqdm=4.49.0
  - typeguard=2.13.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2025a
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - google-genai
